### ISSUE TITLE
gyp ERR! stack Error: Can't find Python executable on Windows

### ISSUE THREAD

**Issue by mtobeiyf** [mtobeiyf/pile#24]
When building on Windows, you might encounter the error

```
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable \"C:\\Users\\Username\\Anaconda3\\python.EXE\", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\\Program Files\
```
even when you have installed Python3.

**Comment by mtobeiyf** [comment]
## Reason: 

node-gyp only support python2.7

## Solution:

### Install `windows-build-tools`

Open powershell as administrator, run
```shell
$ npm install --global --production windows-build-tools
```
This will install python2.7 and visual studio build tools for you

### Set Python 2.7 as default

```
$ npm config set python C:\Users\your_username\.windows-build-tools\python27\python.exe
```

run `yarn` again, the error should be gone

**Comment by mtobeiyf** [comment]
When run `yarn run build` the following error might occur:

```
Error output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.8.2/iojs-v1.8.2.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 52.216.80.112:443
gyp ERR! stack     at Object._errnoException (util.js:1022:11)
gyp ERR! stack     at _exceptionWithHostPort (util.js:1044:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
gyp ERR! System Windows_NT 10.0.16299
```

Download this manually: https://atom.io/download/electron/v1.8.2/iojs-v1.8.2.tar.gz

Extract it to C:\Users\your_username\electron-gyp\iojs-1.8.2\    
**remove the middle v**

run `yarn run build` again
